### ISSUE TITLE
Non-automatic modulefiles don't include `CONDA_ENVIRONMENT_YML`

### ISSUE THREAD

**Issue by rkdarst** [scifihpc/scibuilder-actions#3]
`CONDA_ENVIRONMENT_YML` is in the automatically-generated modulefiles, but not user-provided ones.  Could it somehow be automatically added to all modulefiles by appending to the bottom?

It seems unknown sections in env.yml files are ignored: maybe by using this and extracting out the common fields with yq, all modulefiles can be automatically generated?  Maybe too complex though... I probably wouldn't do it.

```yaml
meta:
  name: blah
  help: blah
name: conda-example
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
```
